### PR TITLE
0.2.0: stop self-registering, ES6ify

### PR DESCRIPTION
**Pull request by Rich-Harris**
This PR completely guts the existing repo and replaces it with a simple ES6 module that exports a bunch of event handlers. In line with other plugins, it will still self-register in a `<script>` soup environment. (Attaching a bunch of different handlers to the `Ractive.events` object requires a nasty hack in the build definition - whether it's worth fixing upstream is a question I'll leave for another day.)

It currently lacks tests, and the demo page has been removed (I'm thinking we should integrate plugin demos into ractivejs.org - would be nice to have plugins.ractivejs.org, just need to spend a bit of time thinking about how to go about building that in the lowest-maintenance way possible). But neither of those things justifies delaying this release.

### CODE REVIEW

**Comment by MartinKolarik** [comment]
Can we have the minified version back in the repo? I noticed it's gone from all recently updated plugins.

**Comment by Rich-Harris** [comment]
@MartinKolarik Yep, done. Will do with it the others as I get round to them, though by all means update any that you need sooner than that, they just need something like [this](https://github.com/ractivejs/ractive-events-keys/blob/master/gobblefile.js#L22-L28) added to the build definition

**Comment by MartinKolarik** [comment]
Ah, that was simple, thanks! Search on npm could certainly use some improvement. I was looking for `gobble-uglify` the other day and found everything but `gobble-uglifyjs`

**Comment by Rich-Harris** [comment]
Ha! One day there'll be a website for gobble with plugins listed... one day. (Need to finish writing the damn thing first.) Thanks for sorting the release tag btw, I always forget to do that

**Comment by MartinKolarik** [comment]
No problem :smile:

**Pull request merged**
